### ISSUE TITLE
My Publish will no be affected on spinnaker

### ISSUE THREAD

**Issue by KeisukeYamashita** [robzienert/tiller#35]
I made a GCE instance with cloud laucher.
Then I connected to this by ssh and port forward.

```bash
gcloud compute ssh --project={PROJECT] --zone=asia-northeast1-a [INSTANCE_NAME] -- -L 9000:localhost:9000  -L 8084:localhost:8084
```
The GUI is working good and I could execute pipeline created with the UI.

I wanted to program my pipeline so I ran this command 

```bash
env SPINNAKER_API=http://localhost:8084 \
go run cmd/roer/main.go pipeline-template publish examples/wait-template.yml
```

This returns this log but nothing is changed on the UI.

```bash
INFO[0000] Publishing template
INFO[0000] Waiting for task to complete...               refURL=/tasks/ac11a77c-2222-4e18-93dd-f017f7fbef6e
INFO[0001] Pipeline has completed
INFO[0001] Task completed                                status=SUCCEEDED
```

I you tell me how I can fix this?

My version of roer is `dev`.

**Comment by mpires** [comment]
This is also happening with me. If you use the `verbose` flag, you will see an error
```
No StageDefinitionBuilder implementation for createPipelineTemplate found
```
Still trying to figure out why. But this is not a problem of this tool, it's on the orca/spinnaker side

**Comment by KeisukeYamashita** [comment]
Is my port `8084` right? The example written int README.md is `7072`

@mpires 
I am also having the same error. Can you check this out? May be helpful.
https://github.com/spinnaker/spinnaker/issues/1834

I am also still trying to figure out why

**Comment by mpires** [comment]
@KeisukeYamashita yes I'm using 8084 as well, it's the correct port for this.

Are you using spinnaker's latest version? I'm using 1.5.4 and I think that's why it's not working for me, but I'm holding off updating to the latest for now.

**Comment by KeisukeYamashita** [comment]
@mpires Thanks. 
It worked after I ran these commands.

```bash
hal config features edit --pipeline-templates true
hal deploy apply
```

Yeah, I am. I am using `v1.7.1`

It seems like the roer returns `status=SUCCEEDED` if the http response status from the Gate API is `200` . 
See here in [action.go](https://github.com/spinnaker/roer/blob/40ea035ad28a5d74486ac403db70431cd7d60b34/actions.go#L394-L402).

And a guy at slack said that the Gate API returns `200` even if the `feature --pipeline-template` is `false`. Please check your hal features.

This command might be helpful.

```bash
hal config features | grep pipelineTemplates
```

**Comment by mpires** [comment]
Thank you very much for that follow up @KeisukeYamashita, that also worked for me.

**Comment by KeisukeYamashita** [comment]
@mpires Good for you.

**Comment by KeisukeYamashita** [comment]
@All of you who encounter this problem.

I'll close this issue.
Make sure that you enable `--pipeline-template` before publishing your template.

**Comment by KeisukeYamashita** [comment]
@mpires BTW, is your `pipeline save` is working too?
It returns `200` but nothing changes in my UI.

**Comment by mpires** [comment]
I'm using this tool for just templates so I can't tell if `pipeline save` works. Try using with `--verbose`, almost definitely Spinnaker is spewing errors and that `200` is a false positive

**Comment by KeisukeYamashita** [comment]
@mpires Okay, thanks so much for your help!
